### PR TITLE
Symbench benchmarks

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
Can you post your output? I am getting on my slow laptop:
```
		 CSymPy
Time for R1 	 0.00117492675781 s
Time for R2 	 0.0469648838043 s
Time for R3 	 3.09944152832e-05 s
Time for R5 	 1.19209289551e-05 s
```

**Comment by isuruf** [comment]
```
isuru@isuru:~/projects/csympy/benchmarks$ python symbench.py sympy
                 CSymPy                  SymPy
Time for R1      0.000679969787598 s     0.164288043976 s
Time for R2      0.0130169391632 s       0.0861639976501 s
Time for R3      1.8835067749e-05 s      7.86781311035e-06 s
Time for R5      5.96046447754e-06 s     1.09672546387e-05 s
```

**Comment by isuruf** [comment]
Added the synthetic benchmarks as well.
```
isuru@isuru:~/projects/csympy/benchmarks$ python symbench.py sympy
                 CSymPy                  SymPy
Time for R1      0.00075101852417 s      0.151736021042 s
Time for R2      0.0123407840729 s       0.100911140442 s
Time for R3      2.31266021729e-05 s     6.91413879395e-06 s
Time for R5      6.91413879395e-06 s     1.09672546387e-05 s
Time for S1      0.0180578231812 s       2.53874707222 s
Time for S2      0.0241491794586 s       9.41651201248 s
Time for S3      0.0204589366913 s       1.44613718987 s
Time for S3a     2.10259413719 s         Test not run s
```

**Comment by thilinarmtb** [comment]
@isuruf: This is great !! Thanks for this.

**Comment by certik** [comment]
We should also benchmark Sage in these benchmarks. The idea is that in Python, we should benchmark codes in Python, e.g. CSymPy, SymPy and Sage.

Then we should have C++ benchmarks. There we should benchmark at least CSymPy and GiNaC.

Another comment is whether it is a good idea to run the benchmarks from one script, or whether we want to launch an external python for each test. Sometimes longer scripts become slower, probably due to memory access.

**Comment by isuruf** [comment]
Will add Sage and C++ benchmarks

About running all the tests within one script, are you suggesting we have a script for each test and call them from another script or a python script that calls the current script for each test (`python symbench.py R1`, `python symbench.py R2`, etc)

**Comment by certik** [comment]
Thanks. What I meant is that when you run 5 benchmarks using the same Python session, the later benchmarks might run slower than if you run them as the only thing in the script. So I thought it might be a good idea to run a separate Python session for each benchmark. Of course, there should be a simple control script to run all of them. The other view that one can take is to just say that we really want csympy to work in a longer Python session, and so it's more representative to run all the benchmarks from one session. I am still leaning towards a script per benchmark, and perhaps one can load them into one session if one wanted to simulate such a run.

**Comment by certik** [comment]
Thanks! Can you post your results using all three?

**Comment by isuruf** [comment]
```
suru@isuru:~/projects/csympy/benchmarks$ python symbench.py sympy sage
Time for R1      CSymPy :      0.00066423 s      SymPy  :      0.14357901 s      Sage   :    0.0044119358 s
Time for R2      CSymPy :      0.02706814 s      SymPy  :      0.09750199 s      Sage   :    0.2184009552 s
Time for R3      CSymPy :      0.00001597 s      SymPy  :      0.00000811 s      Sage   :    0.0002391338 s
Time for R5      CSymPy :      0.00000691 s      SymPy  :      0.00002003 s      Sage   :    0.0281481743 s
Time for S1      CSymPy :      0.01834798 s      SymPy  :      2.52634192 s      Sage   :    0.1464669704 s
Time for S2      CSymPy :      0.02388787 s      SymPy  :      9.31213713 s      Sage   :    0.2697858810 s
Time for S3      CSymPy :      0.02070594 s      SymPy  :      1.58386302 s      Sage   :    0.1418960094 s
Time for S3a     CSymPy :      2.09762287 s                                      Sage   :   14.9792959690 s
```

**Comment by isuruf** [comment]
Using `sage 6.4.1` and `sympy 0.7.5-git`

**Comment by certik** [comment]
I am getting:
```
ondrej@eagle:~/repos/csympy/benchmarks(pr-374)$ PYTHONPATH=.. python symbench
  File "symbench", line 1
SyntaxError: Non-ASCII character '\xc9' in file symbench on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by certik** [comment]
I am getting on my laptop:
```
ondrej@eagle:~/repos/csympy/benchmarks(pr-374)$ PYTHONPATH=.. python symbench.py sympy
Time for R1	 CSymPy :     0.000841141 s	 SymPy  :     0.214595079 s
Time for R2	 CSymPy :     0.038137913 s	 SymPy  :     0.134900808 s
Time for R3	 CSymPy :     0.000020981 s	 SymPy  :     0.000012159 s
Time for R5	 CSymPy :     0.000007153 s	 SymPy  :     0.000014067 s
Time for S1	 CSymPy :     0.022222042 s	 SymPy  :     4.211093903 s
Time for S2	 CSymPy :     0.029553890 s	 SymPy  :    13.474323988 s
Time for S3	 CSymPy :     0.026800156 s	 SymPy  :     1.869362116 s
Time for S3a	 CSymPy :     2.898377180 s				
ondrej@eagle:~/repos/csympy/benchmarks(pr-374)$ ./symbench
2068us
16472us
2us
5us
24286us
31035us
26362us
2.75824e+06us
```

**Comment by isuruf** [comment]
Yes, I noticed that too. `R1, S1, S2, S3, S3a` are slower than the Python ones.

**Comment by certik** [comment]
And R3 is faster in SymPy.

**Comment by certik** [comment]
I would adjust the C++ output to be similar to the Python output, but otherwise this looks good to me.

**Comment by isuruf** [comment]
```
isuru@isuru:~/projects/csympy/benchmarks$ ./symbench_ginac
Time for R1 :        9.078088352
Time for R2 :        0.015011056
Time for R3 :        0.000003073
Time for R4 :        0.000031359
Time for S1 :        0.037988210
Time for S2 :        0.075487462
Time for S3 :        0.027604139
Time for S3a :       2.170938707
```

```
isuru@isuru:~/projects/csympy/benchmarks$ ./symbench
Time for R1 :        0.002495569
Time for R2 :        0.013004237
Time for R3 :        0.000003073
Time for R4 :        0.000005518
Time for S1 :        0.018381039
Time for S2 :        0.026061345
Time for S3 :        0.021999655
Time for S3a :       2.234145347
```

**Comment by certik** [comment]
Nice. Only the S3a is faster in ginac. Interesting, the `Add.diff()` seems pretty optimized: https://github.com/sympy/csympy/blob/master/src/add.cpp#L357

**Comment by isuruf** [comment]
I think we are doing more simplifications automatically than GiNac.

**Comment by certik** [comment]
Which simplifications are we doing that GiNaC doesn't do?

**Comment by isuruf** [comment]
#238 is an example. I installed GiNaC only today. Will play with it and let you know.

**Comment by certik** [comment]
I see. The #238 actually might not necessarily slow things down, since this is embedded in our dictionary representation. But I can see now that ginac is using a different representation that might have different efficiency properties.

**Comment by certik** [comment]
With regards to ginac, make sure you compile it with the same compiler and compiler options (if possible). That can make a huge difference.

**Comment by thilinarmtb** [comment]
`GiNaC` uses a vector of terms and coefficients If I am not mistaken. `add` class and `mul` class inherit from a common class called [expairseq](https://github.com/AlexeiSheplyakov/GiNaC/blob/master/ginac/expairseq.h). There is a comment on this design decision in the above file as well.

**Comment by certik** [comment]
I just want to say that this looks good, in this PR, let's keep all the benchmarks in one file, as you have them. 

We'll have to add a lot more benchmarks, see #364. Any ideas how to best organize it?

**Comment by certik** [comment]
I am +1 to merge this, if you think it's ready.

**Pull request merged**
