### PR TITLE
Run Python tests when installed using make install

### LINKED ISSUE #390: ImportError: No module named 'csympy.compatibility'
This is what I get when I type `import csympy' in Python 3.4:

Traceback (most recent call last):
  File "pathforcer.py", line 14, in <module>
    from csympy import Symbol, symbols, solve, Add
  File "/usr/lib/python3.4/site-packages/csympy/__init__.py", line 3, in <module>
    from .utilities import var, symbols
  File "/usr/lib/python3.4/site-packages/csympy/utilities.py", line 2, in <module>
    from .compatibility import string_types
ImportError: No module named 'csympy.compatibility'

### PR DESCRIPTION
**Pull request by certik**
Fixes #390.

TODO:

* [x] Make sure the tests fail on Travis due to #390 (if they fail for other reason, fix this PR first)
* [x] Merge #391 into this PR to show that it fixes the failure on Travis
* [x] Fix all other unrelated failures that only show after the previous point is fixed

### CODE REVIEW

**Comment by certik** [comment]
According to this: https://travis-ci.org/certik/csympy/jobs/49476635, it looks like the test is working (i.e. fails for the right reason).

**Comment by isuruf** [comment]
+1. Can you merge first commit of #391 into this PR?

**Comment by certik** [comment]
Sure, it's in.

**Comment by certik** [comment]
I expect it to fail, because we actually don't install any tests using `make install`. So that will have to be fixed.

**Comment by isuruf** [comment]
Ah yes. The tests failed earlier because `__init__.py` couldn't import `compatibility.py`. Now that it is there, it doesn't fail. (Although python tests are not run)

**Comment by certik** [comment]
Looks like Travis only tests the latest patch in a PR, not the actual commit, that's why they succeed. But they clearly failed on my own Travis account as I posted above (https://github.com/sympy/csympy/pull/392#issuecomment-72885181), so I think that's a sufficient proof that things work as expected.

The tests actually "run" by executing 0 tests, which I think is fine for now and if all test pass, I'll merge this PR, as it fixes an important bug.

After that we'll figure out how to include all the tests.

**Comment by certik** [comment]
Tests pass, merging.

**Pull request merged**
