### PR TITLE
Fix Issue#380-Missing parentheses

### PR DESCRIPTION
**Pull request by Sumith1896**
My first patch.Any suggestions/help would be great.

### CODE REVIEW

**Comment by sushant-hiray** [comment]
@Sumith1896 thanks for the fix. Can you also add a test so that the given issue can be checked?
Let me know if you need any help in adding tests.

**Comment by certik** [comment]
Thanks for the fix @Sumith1896! As @sushant-hiray said, if you could add a test, that would be great.

**Comment by Sumith1896** [comment]
test_printing.cpp has been updated with three more tests related to the fix of this issue.

**Comment by Sumith1896** [comment]
@certik @sushant-hiray Let me know if anything has to be added.

**Comment by sushant-hiray** [comment]
@Sumith1896 this looks good. :smile: 
Can you change the commit messages and make them more clear?
Try to follow [this](https://github.com/sympy/sympy/wiki/Development-workflow#writing-commit-messages) standards from Sympy.
Refer to [this](https://github.com/sympy/sympy/wiki/Development-workflow#id45) link on changing commit messages.

**Pull request closed without merging**
