### PR TITLE
[WIP] Change EvalDoubleVisitor to use BaseVisitor

### PR DESCRIPTION
**Pull request by isuruf**
This PR is to see whether changing from Visitor to BaseVisitor will affect the performance of EvalDoubleVisitor. If not, I'll change all the Visitors to BaseVisitor.

For me, I noticed no slowdown using gcc.

@certik

### CODE REVIEW

**Comment by thilinarmtb** [comment]
master:
```
thilina@thilina-Inspiron:csympy$ benchmarks/eval_double1 
8362ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
thilina@thilina-Inspiron:csympy$ benchmarks/eval_double1 
8457ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
thilina@thilina-Inspiron:csympy$ benchmarks/eval_double1 
8300ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
```

this branch:
```
thilina@thilina-Inspiron:csympy$ benchmarks/eval_double1 
8293ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
thilina@thilina-Inspiron:csympy$ benchmarks/eval_double1 
8184ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
thilina@thilina-Inspiron:csympy$ benchmarks/eval_double1 
8613ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
```

**Comment by abinashmeher999** [comment]
@isuruf Is 'visitor' here same as 'visitor' in the Visitor Design Pattern?

**Comment by certik** [comment]
@abinashmeher999 yes.

**Comment by isuruf** [comment]
@certik, I removed the methods that were throwing not implemented errors into one method for Basic, but I think it's better to keep them there so that we do not miss some Basic classes when we extend the functionality to include `Log`, `ASinh` etc.

**Comment by certik** [comment]
@isuruf what is the danger? It will raise an exception at runtime. I think that is fine. I think it's better to have less code.

**Comment by isuruf** [comment]
No danger. We could have a TODO comment for the classes to be implemented.
I implemented most of the remaining functions in eval_double. I'll send a PR, once this issue is merged or closed.

**Comment by certik** [comment]
So with gcc 4.9.2 on my computer, master is:
```
certik@redhawk:~/repos/csympy(master)$ benchmarks/eval_double1 
4441ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(master)$ benchmarks/eval_double1 
4415ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(master)$ benchmarks/eval_double1 
4419ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(master)$ benchmarks/eval_double1 
4431ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(master)$ benchmarks/eval_double1 
4570ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(master)$ benchmarks/eval_double1 
4477ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(master)$ benchmarks/eval_double1 
4448ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
```
this PR is:
```
certik@redhawk:~/repos/csympy(pr-428)$ ./benchmarks/eval_double1 
4758ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(pr-428)$ ./benchmarks/eval_double1 
4596ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(pr-428)$ ./benchmarks/eval_double1 
4590ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(pr-428)$ ./benchmarks/eval_double1 
4588ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(pr-428)$ ./benchmarks/eval_double1 
4546ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(pr-428)$ ./benchmarks/eval_double1 
4505ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(pr-428)$ ./benchmarks/eval_double1 
4602ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
```
And for comparison, enabling the single dispatch:
```diff
diff --git a/src/eval_double.cpp b/src/eval_double.cpp
index ce05bef..e3c0d29 100644
--- a/src/eval_double.cpp
+++ b/src/eval_double.cpp
@@ -23,7 +23,7 @@ namespace CSymPy {
  * default. To instead use single dispatch, uncomment the
  * CSYMPY_SINGLE_DISPATCH define below.
  */
-// #define CSYMPY_SINGLE_DISPATCH
+#define CSYMPY_SINGLE_DISPATCH
 
 class EvalDoubleVisitor : public BaseVisitor<EvalDoubleVisitor> {
 private:
```
one gets:
```
certik@redhawk:~/repos/csympy(pr-428)$ ./benchmarks/eval_double1 
4621ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(pr-428)$ ./benchmarks/eval_double1 
4905ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(pr-428)$ ./benchmarks/eval_double1 
4793ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(pr-428)$ ./benchmarks/eval_double1 
4583ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(pr-428)$ ./benchmarks/eval_double1 
4852ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(pr-428)$ ./benchmarks/eval_double1 
4793ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/csympy(pr-428)$ ./benchmarks/eval_double1 
4909ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
```
So using the fastest times in each, this PR is about 2% slower than master, and the single dispatch is about 4% slower.

I am not against merging it. But overall, I really like the single dispatch, especially I think it can get faster by storing the class type as a variable, instead of a virtual function as we do know (I would really like to try it out soon, so that we get an idea about the possible speedup). Few percent slowdown I think is fine.

This PR is my second preference. The original visitor pattern is third, though it is the fastest.

**Comment by certik** [comment]
Anyway, to move forward, I am +1 to merge it, we can currently use any of the three approaches in the code.

**Comment by isuruf** [comment]
Thanks for the review. Storing the type code should give a speedup for single dispatch. Let's look at how it affects the other benchmarks.

**Pull request merged**
