### PR TITLE
Fix Add::diff

### PR DESCRIPTION
**Pull request by isuruf**
Handle case where result of arg diff is a Add

### CODE REVIEW

**Comment by certik** [comment]
Thanks for finding this bug --- looks like I completely forgot about `p.second`, didn't I?

**Comment by certik** [comment]
So I tested the PR, and the test that you added passes in master. We need to find a counter example that fails in master, that your patch fixes it.

**Comment by isuruf** [comment]
Sorry about that. Just adding `one` to `r1` produces the failure.

**Comment by certik** [comment]
Ok, I'll try it tonight.

**Comment by certik** [comment]
Cool, I checked it and now the new test fails in master. So it is +1 to merge if tests pass.

**Pull request merged**
