### PR TITLE
Use single dispatch for eval_double()

### PR DESCRIPTION
**Pull request by certik**
TODO:

* [x] Merge #388 first
* [x] Rebase this PR on top of master
* [x] Benchmark master and this PR using the `eval_double1` benchmark (added in #388), only merge if there is no slowdown

### CODE REVIEW

**Comment by certik** [comment]
On my laptop (gcc 4.8.2), in master (6c718d8bf6d8b2c0c1cd2b2549c99eaa7dfb8d2d)
```
ondrej@eagle:~/repos/csympy/benchmarks(master)$ ./eval_double1 
10040ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
ondrej@eagle:~/repos/csympy/benchmarks(master)$ ./eval_double1 
10126ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
ondrej@eagle:~/repos/csympy/benchmarks(master)$ ./eval_double1 
10185ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
ondrej@eagle:~/repos/csympy/benchmarks(master)$ ./eval_double1 
10163ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
ondrej@eagle:~/repos/csympy/benchmarks(master)$ ./eval_double1 
10209ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
ondrej@eagle:~/repos/csympy/benchmarks(master)$ ./eval_double1 
10295ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
```

and this PR (0be6222e34cd2e5f74bd2450805ca330b75bdc64):
```
ondrej@eagle:~/repos/csympy/benchmarks(eval_double_single_dispatch)$ ./eval_double1 
9953ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
ondrej@eagle:~/repos/csympy/benchmarks(eval_double_single_dispatch)$ ./eval_double1 
10048ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
ondrej@eagle:~/repos/csympy/benchmarks(eval_double_single_dispatch)$ ./eval_double1 
9594ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
ondrej@eagle:~/repos/csympy/benchmarks(eval_double_single_dispatch)$ ./eval_double1 
9651ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
ondrej@eagle:~/repos/csympy/benchmarks(eval_double_single_dispatch)$ ./eval_double1 
9585ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
ondrej@eagle:~/repos/csympy/benchmarks(eval_double_single_dispatch)$ ./eval_double1 
9630ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
```
So if I take the best timing in both, this PR causes 4.7% slowdown.

I'll benchmark on other computers soon.

**Comment by isuruf** [comment]
This PR 0be6222e34cd2e5f74bd2450805ca330b75bdc64
```
7290ms
7096ms
7114ms
7389ms
```

Master
```
6921ms
7054ms
7032ms
6902ms
```

**Comment by certik** [comment]
Thanks @isuruf. So you got 2.8% slowdown (taking the best time of both).

I benchmarked again on the same laptop, this time I got in master:
```
10160ms
10172ms
10238ms
10102ms
10315ms
10292ms
```
and this PR:
```
9830ms
9432ms
10066ms
10266ms
10000ms
```
Taking the best time of each, now this PR is 6.6% faster. So this just shows that my laptop is unreliable for benchmarking when it comes to differences like ~5%.

**Comment by thilinarmtb** [comment]
On my ubuntu (14.04) laptop using gcc (4.8.2), this PR:
```
9206ms
9423ms
9278ms
9157ms
9416ms
```
avg: 9296

master:
```
8726ms
8778ms
8833ms
8689ms
8793ms
```
avg: 8763.8

**Comment by certik** [comment]
@isuruf, @thilinarmtb thanks for trying this out. So on your laptops, this PR is a bit slower. On all my computers this PR seems a bit faster.

Let me know what you think we should do. We can keep both visitor pattern and single dispatch in there for now and remove one later. Maybe there is a way to modify the code so that it is faster on your laptops as well.

In the meantime, I'll try to benchmark this on more computers.

**Comment by thilinarmtb** [comment]
The difference is very small with clang  in my laptop. But with gcc, the performance has degraded considerably. If this PR is faster on other machines, then I think this is the way to go. Most probably the issue is caused by compilers doing something strange on laptops. For the time being my idea is that we shall keep the both, and later figure out why this happen and how to fix it.

**Comment by certik** [comment]
On another computer, gcc 4.8.2, master:
```
5078ms
5133ms
5076ms
5066ms
5145ms
5269ms
5220ms
5134ms
5134ms
5156ms
```
min=5066, avg=5141.1
this PR
```
5308ms
5117ms
5133ms
5088ms
5022ms
5184ms
5125ms
5301ms
5311ms
5031ms
```
min=5022, avg=5162.0
So here the minimum is 0.9% better, the average is 0.4% worse.

**Comment by certik** [comment]
@thilinarmtb I agree. I've added the visitor pattern back in and made it the default. Let me know if you are ok with merging it as it is now.

That way we have both implementations in and we can play with those later. Yes, my own laptop is not very reliable for benchmarking. If you ever get to it, try the very latest gcc version (4.9.2), they might have improved some of the optimizations. I think clang is still catching up with optimizations.

**Comment by thilinarmtb** [comment]
+1 to merge as it is.

I'll try with gcc 4.9.2 as well.

**Comment by Sumith1896** [comment]
On my ubuntu(14.04) machine with gcc 4.8.2
master:
```
6043ms
5998ms
5944ms
6432ms
6066ms
```
min=5944,avg=6096.6
this PR:
```
6111ms
6163ms
6359ms
6085ms
6112ms
```
min=6085,avg=6166

**Comment by jcrist** [comment]
Here's what I get, running Arch Linux, gcc 4.9.2
**Master**
13629ms
14036ms
13516ms

mean: 13727.0

**This PR**
14030ms
13971ms
13900ms

mean: 13967.0

I only ran each 3 times, but it looks about the same. Stats on such a small sample are pretty worthless, probably should have ran it a few more times...

**Comment by certik** [comment]
Thanks @Sumith1896 and @jcrist. Since you tested after cec0dc393eb62b782eeeef1617ac95b752aec306 was added, make sure you enable the single dispatch by manually doing the change:
```diff
diff --git a/src/eval_double.cpp b/src/eval_double.cpp
index d0aa72b..6b638c9 100644
--- a/src/eval_double.cpp
+++ b/src/eval_double.cpp
@@ -23,7 +23,7 @@ namespace CSymPy {
  * default. To instead use single dispatch, uncomment the
  * CSYMPY_SINGLE_DISPATCH define below.
  */
-// #define CSYMPY_SINGLE_DISPATCH
+#define CSYMPY_SINGLE_DISPATCH
 
 class EvalDoubleVisitor : public Visitor {
 private:
```
Currently the single dispatch is off, until we figure out what the slight slowdown on some platforms is caused by.

Tests pass, so I am merging this PR.

**Pull request merged**
