### PR TITLE
Replace x with getarg() in Inverse hyperbolic Functions

### PR DESCRIPTION
**Pull request by aktech**
As seen in #427 

@sushant-hiray @certik @isuruf

### CODE REVIEW

**Comment by isuruf** [comment]
+1

**Comment by isuruf** [comment]
A test with `arg` not equal to `x` or `-x` needs to be added.

**Comment by isuruf** [comment]
@aktech, 
Tests you added pass on master as well. We need to add a test that fails on master, but is fixed by your PR.

**Comment by aktech** [comment]
@isuruf 

This PR is probably not a bug fix. 
The code [here](https://github.com/sympy/csympy/blob/master/src/functions.cpp#L2011):

```cpp
RCP<const Basic> ASinh::diff(const RCP<const Symbol> &x) const
{
    return mul(div(one, sqrt(add(pow(x, i2), one))), get_arg()->diff(x));
}
```
accepts the argument and stores it at the address &x , so whatever symbol variable we may pass it would work fine, without this PR also. The point of replacing `x` with `get_arg()` is that it is more generic, & also it was suggested [here](https://github.com/sympy/csympy/pull/427#discussion_r29100896) as well.

I may be wrong, but I am not sure what else could be added here.

**Comment by isuruf** [comment]
@aktech, point of replacing `x` with `get_arg()` is that the result of `asinh(2*x)->diff(x)` which is `2/(1 + 4*x**2)**(1/2)` is given as `2/(1 + x**2)**(1/2)` in master, so this PR is an important bug fix.

**Comment by aktech** [comment]
@isuruf 

Thanks, for enlightening me on this!
I would make the changes.

**Comment by isuruf** [comment]
Thanks for the fix. Sorry about the confusion.
I am + 1 to merge. @certik @thilinarmtb ?

**Comment by certik** [comment]
@aktech thanks for fixing it, thanks @isuruf for the review.

**Pull request merged**
