### PR TITLE
Remove hack for miniconda glibc issue

### PR DESCRIPTION
**Pull request by isuruf**
Issue in miniconda seems to be fixed now.
Keeping the hack, fails the tests in shippable.

### CODE REVIEW

**Comment by pbrady** [comment]
Is there a PR that fixed the conda/libm issue that can be linked to?

**Comment by asmeurer** [comment]
The Anaconda repo that has the recipe for the `system` conda package with the old libm is private. But I can verify that if you `conda update system` it will no longer have the old libm.

**Comment by isuruf** [comment]
`conda update -q conda;` is enough right?

Some of the shippable build jobs fail because of an internal error. I restarted twice and different tests fail.

**Comment by isuruf** [comment]
Shippable builds are passing now.

**Comment by certik** [comment]
Thanks @isuruf, +1 to merge.

**Comment by asmeurer** [comment]
Strictly speaking, updating conda doesn't give the updated libm. But it works because shippable always starts from scratch so it grabs the updated libm (which is probably coming from a dependency of cython).

**Comment by asmeurer** [comment]
Oh, `system` (the conda package with libm) is a dependency of `python`.

**Pull request merged**
