### PR TITLE
Make tests independent of size of size_t

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
At the moment our test suite does not check for this as Travis and Shippable both use 64-bit systems. We could test it on Appveyor with mingw32. See [sample](https://ci.appveyor.com/project/isuruf/csympy/build/1.0.62)

**Comment by certik** [comment]
The right solution is to implement what SymPy has: printing that is independent of the internal representation (that is platform dependent).

If you need this to continue development, you can merge it, but otherwise we need to implement printers. See here: https://github.com/sympy/sympy/blob/d0d234b90289c5ed4b214fa38aed901244751729/sympy/printing/str.py#L48

**Comment by isuruf** [comment]
Agreed. Will look into it.

**Comment by certik** [comment]
I am going to close this PR for now and I have opened a new issue about the printers #377.

**Pull request closed without merging**
