### PR TITLE
Travis-ci: use cpp environment and test clang

### PR DESCRIPTION
**Pull request by isuruf**
Following changes were made to the travis/shippable builds
* Travis - Use cpp environment instead of python
* Shippable - Added shippable.yml which uses python environment (though Miniconda is used to install python) since shippable does not support cpp
* Use Miniconda to install python (2.6, 2.7, 3.3, 3.4)
* Removed python 3.2 tests as miniconda does not support it.
* Travis - Added a test in clang
* Added `-Wno-constant-logical-operand` flag for Travis/Shippable builds

### CODE REVIEW

**Comment by isuruf** [comment]
@certik any other comments?

**Comment by certik** [comment]
Thanks @isuruf for finishing this up. I want to review this more carefully, as it is very important not to make any mistake in the testing infrastructure. I am traveling to the US tomorrow, so I need few more days. I'll get to it soon.

**Comment by certik** [comment]
Actually, I went over it and I think it looks good. Thanks for figuring out how to use miniconda, I think it sped up the builds a lot.

The only issue I have is that Shippable's config is now duplicate, but not exact duplicate of Travis. I was thinking that maybe we can have an install script, e.g. `bin/travis_install.sh` that will do the installation of packages like Arb, based on the env options. And the shippable and Travis yaml files will be very short, reusing most of the functionality between them.

**Comment by isuruf** [comment]
Yes, I agree.  `.travis.yml` and `shippable.yml` still needs to have the environment options duplicate, right?

**Comment by certik** [comment]
Before this PR, Travis and Shippable were exactly equivalent. After this PR, Shippable is a subset of Travis, it only does gcc testing. As such, it should be possible to extract all installation into a script and reuse it. From the configuration point of view, Shippable uses the Python environment, while Travis uses the C environment, so the yaml file is different, but I think both yaml files could be just used to setup the environment variables properly and then just call a common script.

The only question is whether we should do it as part of this PR or rather merge this first, since it works, and do another PR. I think another PR is probably the way to go, so that we can merge this and start using it. Let me know what you think.

**Comment by isuruf** [comment]
It's easier to send the changes in this PR. I pushed in the changes to call a common script to install libraries. Travis tests pass and shippable is still running the tests.

**Comment by isuruf** [comment]
Last four shippable jobs in the build are marked as failure although all tests are successful.

**Comment by thilinarmtb** [comment]
I restarted the tests.

**Comment by certik** [comment]
It's weird, the 3 Shippable jobs failed, but when you click on them, they seemed to succeed.

**Comment by certik** [comment]
Thanks for the fix, that's exactly what I had in mind. We just need to figure out why Shippable is failing.

**Comment by isuruf** [comment]
The script was run as `source bin/test_travis.sh` in the commit that failed. When I removed source, it worked fine in Shippable.

**Comment by isuruf** [comment]
@certik, clang tests pass when `CWrapper` is declared as a struct

**Comment by certik** [comment]
Thanks! I went over it and I think it looks good. I have no other objections, so I am merging this.

**Pull request merged**
