### PR TITLE
Add out of tree build using setup.py

### PR DESCRIPTION
**Pull request by isuruf**
I normally build out of tree using cmake. To build with sage I can use `sage -python ../../csympy/setup.py install` with this PR.

### CODE REVIEW

**Comment by certik** [comment]
This looks great. @pbrady what do you think?

**Comment by pbrady** [comment]
Looks good to me.  Was there a reason to chose `realpath` over `abspath`.  `realpath` resolves links but `abspath` does not.  My initial hunch is that `abspath` will have less potential surprise (though I can't really imagine how one would run into problems with links during an out of tree build).

**Comment by isuruf** [comment]
No. There was no reason. I didn't know there was a difference.

**Comment by pbrady** [comment]
+1 to merge.  I don't think anyone would ever use a symlinked setup.py anyway.

**Comment by isuruf** [comment]
Merged. Thanks for the review

**Pull request merged**
